/*---
description: account related tables
dialect: mysql 9
---*/

-- account table
CREATE TABLE account
(
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME      VARCHAR(50)  NOT NULL UNIQUE,
    EMAIL         VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD      VARCHAR(255) NOT NULL,
    FIRST_NAME    VARCHAR(50),
    LAST_NAME     VARCHAR(50),
    PHONE         VARCHAR(20),
    STATUS        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN_AT TIMESTAMP NULL
);

CREATE INDEX idx_username ON account (USERNAME);
CREATE INDEX idx_email ON account (EMAIL);
CREATE INDEX idx_status ON account (STATUS);
